table dim_usuarios_rls
	lineageTag: 62498562-f804-4678-909d-d01e7e0a7d34

	column email_usuario
		dataType: string
		lineageTag: c1294d89-a961-48a7-ab0e-c0221595d785
		summarizeBy: none
		sourceColumn: email_usuario

		annotation SummarizationSetBy = Automatic

	column regiao_permitida
		dataType: string
		lineageTag: 0d660527-a9aa-4b27-9d6a-430be382a00a
		summarizeBy: none
		sourceColumn: regiao_permitida

		annotation SummarizationSetBy = Automatic

	partition dim_usuarios_rls = m
		mode: import
		source =
				let
				Fonte = Table.FromRows(
				{
				{"gestor.norte@ministerio.br", "Norte"},
				{"gestor.nordeste@ministerio.br", "Nordeste"},
				{"gestor.centroeste@ministerio.br", "Centro-Oeste"},
				{"gestor.sudeste@ministerio.br", "Sudeste"},
				{"gestor.sul@ministerio.br", "Sul"}
				},
				{"email_usuario", "regiao_permitida"}
				),
				TipoAlterado = Table.TransformColumnTypes(
				Fonte,
				{
				{"email_usuario", type text},
				{"regiao_permitida", type text}
				}
				)
				in
				TipoAlterado

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

